const IMAGES = {
    //Sweets
    samosa: require('../images/samosa.jpg'),
    anjeer: require('../images/anjeerBox.jpg'),
    balusah: require('../images/balusah.jpg'),
    besan: require('../images/besan.jpg'),
    bombay: require('../images/bombay.jpg'),
    cham: require('../images/cham.jpg'),
    champa: require('../images/champa.jpg'),
    chandrakala: require('../images/chandrakala.jpg'),
    coconut: require('../images/coconut.jpg'),
    dodda: require('../images/dodda.jpg'),
    dryBesan: require('../images/dryBesan.jpg'),
    dryBurfi: require('../images/dryBurfi.jpg'),
    dryHalwa: require('../images/dryHalwa.jpg'),
    fruit: require('../images/fruit.jpg'),
    jalebi: require('../images/jalebi.jpg'),
    kaju: require('../images/kaju.jpg'),
    kajuGujiya: require('../images/kajuGujiya.jpg'),
    kajuRoll: require('../images/kajuRoll.jpg'),
    kajuSamosa: require('../images/kajuSamosa.jpg'),
    kala: require('../images/kala.jpg'),
    kalakand: require('../images/kalakand.jpg'),
    kalash: require('../images/kalash.jpg'),
    kesarLaddoo: require('../images/kesarLaddoo.jpg'),
    kesarPeda: require('../images/kesarPeda.jpg'),
    kheerKadam: require('../images/kheerKadam.jpg'),
    kovaRoll: require('../images/kovaRoll.jpg'),
    malaiLaddoo: require('../images/malaiLaddoo.jpg'),
    malaiPeda: require('../images/malaiPeda.jpg'),
    malaiSand: require('../images/malaiSand.jpg'),
    mawaBoondi: require('../images/mawaBoondi.jpg'),
    milkBurfi: require('../images/milkBurfi.jpg'),
    milkCake: require('../images/milkCake.jpg'),
    milkPeda: require('../images/milkPeda.jpg'),
    milkRoll: require('../images/milkRoll.jpg'),
    moti: require('../images/moti.jpg'),
    motichoorLaddoo: require('../images/motichoorLaddoo.jpg'),
    mysore: require('../images/mysore.jpg'),
    paan: require('../images/paan.jpg'),
    pinni: require('../images/pinni.jpg'),
    soan: require('../images/soan.jpg'),
    //Mixtures
    awalakkiMix: require('../images/awalakkiMix.jpg'),
    bombayMix: require('../images/bombayMix.jpg'),
    boondiMix: require('../images/boondiMix.jpg'),
    chips: require('../images/chips.jpg'),
    dalmot: require('../images/dalmot.jpg'),
    gathiya: require('../images/gathiya.jpg'),
    gujratiPapdi: require('../images/gujratiPapdi.jpg'),
    lahsen: require('../images/lahsen.jpg'),
    mathri: require('../images/mathri.jpg'),
    nimkiPlain: require('../images/nimkiPlain.jpg'),
    palakSev: require('../images/palakSev.jpg'),
    plainSev: require('../images/plainSev.jpg'),
    sakarpala: require('../images/sakarpala.jpg'),
    sohali: require('../images/sohali.jpg'),
    spicy: require('../images/spicy.jpg'),

    //Beverages
    chaas: require('../images/chaas.jpg'),
    lassi: require('../images/lassi.jpg'),
    mango: require('../images/mango.jpg'),
    badamMilk: require('../images/badamMilk.jpg'),
}

export default IMAGES;