const IMAGES = {
    //Sweets
    milkMysore: require('../images/milkMysore.jpg'),
    anjeer: require('../images/anjeerBox.jpg'),
    balusah: require('../images/balusah.jpg'),
    besan: require('../images/besan.jpg'),
    bombay: require('../images/bombay.jpg'),
    cham: require('../images/cham.jpg'),
    champa: require('../images/champa.jpg'),
    chandrakala: require('../images/chandrakala.jpg'),
    coconut: require('../images/coconut.jpg'),
    dodda: require('../images/dodda.jpg'),
    dryBesan: require('../images/dryBesan.jpg'),
    dryBurfi: require('../images/dryBurfi.jpg'),
    dryHalwa: require('../images/dryHalwa.jpg'),
    fruit: require('../images/fruit.jpg'),
    jalebi: require('../images/jalebi.jpg'),
    kaju: require('../images/kaju.jpg'),
    kajuGujiya: require('../images/kajuGujiya.jpg'),
    kajuRoll: require('../images/kajuRoll.jpg'),
    kajuSamosa: require('../images/kajuSamosa.jpg'),
    kala: require('../images/kala.jpg'),
    kalakand: require('../images/kalakand.jpg'),
    kalash: require('../images/kalash.jpg'),
    kesarLaddoo: require('../images/kesarLaddoo.jpg'),
    kesarPeda: require('../images/kesarPeda.jpg'),
    kheerKadam: require('../images/kheerKadam.jpg'),
    kovaRoll: require('../images/kovaRoll.jpg'),
    malaiLaddoo: require('../images/malaiLaddoo.jpg'),
    malaiPeda: require('../images/malaiPeda.jpg'),
    malaiSand: require('../images/malaiSand.jpg'),
    mawaBoondi: require('../images/mawaBoondi.jpg'),
    milkBurfi: require('../images/milkBurfi.jpg'),
    milkCake: require('../images/milkCake.jpg'),
    milkPeda: require('../images/milkPeda.jpg'),
    milkRoll: require('../images/milkRoll.jpg'),
    moti: require('../images/moti.jpg'),
    motichoorLaddoo: require('../images/motichoorLaddoo.jpg'),
    mysore: require('../images/mysore.jpg'),
    paan: require('../images/paan.jpg'),
    pinni: require('../images/pinni.jpg'),
    soan: require('../images/soan.jpg'),

    //Chaats
    alooBatata: require('../images/alooBatata.jpg'),
    bhelPuri: require('../images/bhelPuri.jpg'),
    cutletChaat: require('../images/cutletChaat.jpg'),
    cutletMutter: require('../images/cutletMutter.jpg'),
    dahiBatata: require('../images/dahiBatata.jpg'),
    dahiKatori: require('../images/dahiKatori.jpg'),
    dahiPapdi: require('../images/dahiPapdi.jpg'),
    dahiRaj: require('../images/dahiRaj.jpg'),
    jhalMuri: require('../images/jhalMuri.jpg'),
    kachoriChaat: require('../images/kachoriChaat.jpg'),
    kachoriMutter: require('../images/kachoriMutter.jpg'),
    masalaPuri: require('../images/masalaPuri.jpg'),
    papdiChole: require('../images/papdiChole.jpg'),
    papdiMutter: require('../images/papdiMutter.jpg'),
    plainMutter: require('../images/plainMutter.jpg'),
    rasgullaChaat: require('../images/rasgullaChaat.jpg'),
    samosaChaat: require('../images/samosaChaat.jpg'),
    samosaMutter: require('../images/samosaMutter.jpg'),
    sevPuri: require('../images/sevPuri.jpg'),
    tikkiyaMutter: require('../images/tikkiyaMutter.jpg'),
    tomatoChaat: require('../images/tomatoChaat.jpg'),
    
    //Mixtures
    awalakkiMix: require('../images/awalakkiMix.jpg'),
    bombayMix: require('../images/bombayMix.jpg'),
    boondiMix: require('../images/boondiMix.jpg'),
    chips: require('../images/chips.jpg'),
    dalmot: require('../images/dalmot.jpg'),
    gathiya: require('../images/gathiya.jpg'),
    gujratiPapdi: require('../images/gujratiPapdi.jpg'),
    lahsen: require('../images/lahsen.jpg'),
    mathri: require('../images/mathri.jpg'),
    nimkiPlain: require('../images/nimkiPlain.jpg'),
    palakSev: require('../images/palakSev.jpg'),
    plainSev: require('../images/plainSev.jpg'),
    sakarpala: require('../images/sakarpala.jpg'),
    sohali: require('../images/sohali.jpg'),
    spicy: require('../images/spicy.jpg'),

    //Beverages
    chaas: require('../images/chaas.jpg'),
    lassi: require('../images/lassi.jpg'),
    mango: require('../images/mango.jpg'),
    badamMilk: require('../images/badamMilk.jpg'),

    //Snacks
    bhature: require('../images/bhature.jpg'),
    cheeseBhature: require('../images/cheeseBhature.jpg'),
    cheesePavBhaji: require('../images/cheesePavBhaji.jpg'),
    cheeseVada: require('../images/cheeseVada.jpg'),
    choleMethiBhature: require('../images/choleMethiBhature.jpg'),
    cutletVada: require('../images/cutletVada.jpg'),
    mixPavBhaji: require('../images/mixPavBhaji.jpg'),
    paneerBhature: require('../images/paneerBhature.jpg'),
    paneerMethi: require('../images/paneerMethi.jpg'),
    paneerPavBhaji: require('../images/paneerPavBhaji.jpg'),
    paniPuri: require('../images/paniPuri.jpg'),
    pavBhaji: require('../images/pavBhaji.jpg'),
    peasPavBhaji: require('../images/peasPavBhaji.jpg'),
    samosaVada: require('../images/samosaVada.jpg'),
    tikkiVada: require('../images/tikkiVada.jpg'),
    vada: require('../images/vada.jpg'),

    //Parathas
    ajwain: require('../images/ajwain.jpg'),
    aloo: require('../images/aloo.jpg'),
    chapChole: require('../images/chapChole.jpg'),
    chapGobi: require('../images/chapGobi.jpg'),
    chapPaneer: require('../images/chapPaneer.jpg'),
    gobi: require('../images/gobi.jpg'),
    greenPeas: require('../images/greenPeas.jpg'),
    laccha: require('../images/laccha.jpg'),
    methi: require('../images/methi.jpg'),
    methiAlooGravy: require('../images/methiAlooGravy.jpg'),
    mixed: require('../images/mixed.jpg'),
    mooli: require('../images/mooli.jpg'),
    onion: require('../images/onion.jpg'),
    onionCheese: require('../images/onionCheese.jpg'),
    palakAlooGravy: require('../images/palakAlooGravy.jpg'),
    paneer: require('../images/paneer.jpg'),
    paneerCheese: require('../images/paneerCheese.jpg'),
    parChole: require('../images/parChole.jpg'),
    parGobi: require('../images/parGobi.jpg'),
    parPaneer: require('../images/parPaneer.jpg'),
    pudinaAlooGravy: require('../images/pudinaAlooGravy.jpg'),
    puriChole: require('../images/puriChole.jpg'),
    puriGobi: require('../images/puriGobi.jpg'),
    puriPaneer: require('../images/puriPaneer.jpg'),
    sattu: require('../images/sattu.jpg'),
}

export default IMAGES;